### ISSUE TITLE
Scheduled workflows on non-default branches do not run

### ISSUE THREAD

**Issue by colinwilson** [GraphIP/postgres#1]
### Expected Behavior
Scheduled workflows on non default branches to run

### Actual Behavior
Scheduled workflows configured in the non default branches (`13` & `11`) are ignored and do not run. See [docs.github.com](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule):

> You can schedule a workflow to run at specific UTC times using POSIX cron syntax. **Scheduled
> workflows run on the latest commit on the default or base branch**. The shortest interval you can
> run scheduled workflows is once every 5 minutes.

[github.community discussion on the issue](https://github.community/t/scheduled-builds-of-non-default-branch/16306/19)

### Proposal
Reconfigure the default branch (12) workflow to checkout and build the other branches. e.g.
```yaml
on:
  schedule:
    - cron: '0 1 * * wed'  # every wednesday @ 01:00

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 13
      
      # Build steps go here
```
